---
title: |
  | *`r params$TargetTaxon`* in `r params$UnitName`
author: "M.C. Rosa G. Pérez-Hernández; Ph.D. Mario Hernández Guzmán"
date: "2022-10-28"
output:
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: no
    theme: united
    toc_float: yes
    hightlight: kate
    df_print: paged
  pdf_document:
    toc: yes
    toc_depth: '3'
params:
  TargetTaxon: Piper auritum
  UnitName: rural communities from Yucatán, México
---

## 1. Configuración de la sesión y carga de paqueterías

```{r setup, include=TRUE, message=FALSE, eval=FALSE}
## environment
set.seed(123999)
options(scipen = 10000, digits = 3, ggrepel.max.overlaps = Inf)
library(tidyverse, warn.conflicts = F)
library(patchwork)
library(vegan); 
library(FactoMineR)
```

## 2. Cargando sesiones de R

```{include=TRUE, message=FALSE, eval=FALSE}
base::load(file = 'rdatabases/Figs_2-y-4_Usos-y-Manejos.RData')
base::load(file = 'rdatabases/Fig.5-PCA-aceites-esenciales.RData')
source(file = 'scripts/plot_setts.R')
```

## 3. Figura 2: Índices de sutrop

```{r, eval=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=50)}
# 1. Reading raw databae: excel data; check for additional details --------
	## Data were taken from the Excel database: check data out for any additional detail

	sutrop <- xlsx::read.xlsx (file = 'data/p_auritum_database.xlsx', sheetIndex = 3, startRow = 3)
	
	sutrop %>% dplyr::as_tibble()
	
	## Filter data and plot:
	## Uso culinario
	culinario <-
	sutrop %>%
		tidyr::pivot_longer(cols = c(-1:-2), names_to = "comunidad", values_to = "sutrop") %>%
		dplyr::filter(Uso == "Culinario") %>% 
		dplyr::mutate(sutrop = dplyr::if_else(sutrop==0, true = 0.01, false = sutrop)) %>%
		ggplot(aes(x = comunidad, y = sutrop, fill = Tipo)) + 
		theme_bw(base_size = 16) +
		labs (y = "Índice de Sutrop\n", x = element_blank()) +
		geom_bar(position = position_dodge(0.9), stat = "identity", width = 0.8) +
		scale_fill_manual(name = element_blank(), 
				  values = RColorBrewer::brewer.pal(n = 5, name = "Dark2"),
				  limits = c("vaporcitos", "con huevos", "con ibes", "Bebida", "cool"),
				  labels = c("Vaporcitos", "+Huevos", "+Íbes", "Bebida", "Co´ol")) +
		scale_y_continuous(expand=c(0,0), 
				   limits = c(0,1.05), 
				   breaks = seq(from = 0, to = 1, by = .1), 
				   labels = c("0.0", "", 0.2, "", 0.4, "", 0.6, "", 0.8, "", "1.0")) +
		scale_x_discrete(name = element_blank(),
				 limits = c("Ebtun", "Ek.Balam", "Hunuku", "Pixoy", "Santa.Rita", "Uayma"),
				 labels = c("Ebtún", "Ek Balam", "Hunuku", "Pixoy", "Santa Rita", "Uayma")) +
		facet_grid(cols = vars (factor(Uso, levels=c("Culinario"), labels = c("Uso culinario")))) +
		guides (fill = guide_legend(ncol = 3)) + 
		plot_setts + theme(legend.position = "bottom") + coord_flip() +
		theme(panel.grid.major.x = element_line(colour = "gray20", linetype = "dashed", linewidth = 0.1))
	

	## Uso Medicinal: plots
	medicinal <- sutrop %>%
		tidyr::pivot_longer(cols = c(-1:-2), names_to = "comunidad", values_to = "sutrop") %>%
		dplyr::filter(Uso == "Medicinal") %>%
		dplyr::mutate(sutrop = dplyr::if_else(sutrop==0, true = 0.005, false = sutrop)) %>%
		ggplot(aes(x = comunidad, y = sutrop, fill = Tipo)) + theme_bw() +
		labs (y = "Índice de Sutrop\n", x = element_blank()) +
		geom_bar(position = position_dodge(0.9), stat = "identity", width = 0.8) +
		scale_fill_manual(name = element_blank(),
				  values = RColorBrewer::brewer.pal(n = 12, name = "Paired"),
				  limits = c("Colesterol", "Diabetes", "Dolor", "Fiebre", "Producir leche", "Gastritis ", "Hemorroides", "Nervios", "Pelagra", "Presión", "Purgante", "Tos"),
				  labels = c("Colesterol", "Diabetes", "Dolor", "Fiebre", "Galactogogo", "Gastritis", "Hemorroides", "Nervios", "Pelagra", "Presión", "Purgante", "Tos")) +
		scale_y_continuous(expand=c(0,0),
				   limits = c(0, 0.31),
				   breaks = seq(0, 0.3, 0.03),
				   labels = c("0.0","", 0.06, "",0.12, "", 0.18, "",0.24, "", 0.3)) +
		scale_x_discrete(name = element_blank(),
				 limits = c("Ebtun", "Ek.Balam", "Hunuku", "Pixoy", "Santa.Rita", "Uayma"),
				 labels = c("Ebtún", "Ek Balam", "Hunuku", "Pixoy", "Santa Rita", "Uayma")) +
		facet_grid(cols = vars (factor(Uso, levels=c("Medicinal"), labels = c("Uso medicinal")))) + 
		guides (fill = guide_legend(ncol = 4)) + 
		theme(legend.position = "bottom") + coord_flip() + plot_setts +
		theme(panel.grid.major.x = element_line(colour = "gray20", linetype = "dashed", linewidth = 0.1))
	
	
	## Merge into one plot with patchwork:
	figure2 <- (culinario + theme(axis.title.x = element_text(size = 14))) | (medicinal + theme(axis.text.y = element_blank(), axis.title.x = element_text(size = 14) ) )
	figure2
	

	## Save as a single plot
	ggplot2::ggsave(filename = 'Figures/Figure-2-Sutrop-Usos.png', dpi = 300, width = 14, height = 6)

```

## 4. Figura 4: Manejos de _Piper auritum_

```{r, eval=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=50)}
# MANEJOS Y USOS DE Piper autirum: Valores porcentuales ----------------


	## 1. Leemos la base de datos, convertimos a formato largo, y posteriormente graficamos
	data <- xlsx::read.xlsx (file = 'data/p_auritum_database.xlsx', sheetIndex = 4, startRow = 3) %>% 
		tidyr::pivot_longer(cols = c(-1:-2), names_to = "comunidad", values_to = "sutrop")
	
	data %>% dplyr::as_tibble()
	
	## Filter data and plot:
	## Origen
	origenes <- data %>%
		dplyr::filter(practice == "Origen") %>%
		dplyr::mutate(sutrop = dplyr::if_else(sutrop==0, true = 0.2, false = sutrop)) %>%
		ggplot(aes(x = comunidad, y = sutrop, fill = type)) + theme_bw() +
		labs (y = "\nValores porcentuales (%)\n", x = element_blank()) +
		geom_bar(position = position_dodge(0.9), stat = "identity", width = 0.8) +
		scale_fill_manual(name = element_blank(), 
				  values = RColorBrewer::brewer.pal(n = 5, name = "Dark2"),
				  limits = c("nacio_solo", "del_monte", "de_otro_huerto"),
				  labels = c("Nació sola", "Monte", "Otro huerto")) +
		scale_y_continuous(expand=c(0,0), limits = c(0,31), breaks = seq(0,30,3), 
				   labels = c("0.0","",6,"",12,"",18,"",24,"",30)) +
		scale_x_discrete(name = element_blank(),
				 limits = c("Ebtun", "Ek_Balam", "Hunuku", "Pixoy", "Santa_Rita", "Uayma"),
				 labels = c("Ebtún", "Ek Balam", "Hunuku", "Pixoy", "Santa Rita", "Uayma")) +
		facet_grid(cols = vars (factor(practice, levels=c("Origen"), labels = c("Origen")))) +
		guides (fill = guide_legend(nrow = 1)) + plot_setts + 
		theme(legend.position = "bottom",
		      panel.grid.major.y = element_blank(),
		      panel.grid.major.x = element_line(color = "gray40", linewidth = 0.1, linetype = "dashed")) + coord_flip()
	
	## Manejos: Plotting:
	manejos <- data %>%
		dplyr::filter(practice == "Manejo") %>%
		dplyr::mutate(sutrop = dplyr::if_else(sutrop==0, true = 0.005, false = sutrop)) %>%
		ggplot(aes(x = comunidad, y = sutrop, fill = type)) + theme_bw() +
		labs (y = "\nÍndice de Sutrop\n", x = element_blank()) +
		geom_bar(position = position_dodge(0.9), stat = "identity", width = 0.8) +
		scale_fill_manual(name = element_blank(), 
				  values = RColorBrewer::brewer.pal(n = 5, name = "Dark2"),
				  limits = c("Riego", "Chapeo", "Poda"),
				  labels = c("Riego", "Deshierbe", "Poda")) +
		scale_y_continuous(expand=c(0,0), limits = c(0,1.1), breaks = seq(0,1,.1),
				   labels = c("0.0","",0.2,"",0.4,"",0.6,"",0.8,"","1.0")) +
		scale_x_discrete(name = element_blank(),
				 limits = c("Ebtun", "Ek_Balam", "Hunuku", "Pixoy", "Santa_Rita", "Uayma"),
				 labels = c("Ebtún", "Ek Balam", "Hunuku", "Pixoy", "Santa Rita", "Uayma")) +
		facet_grid(cols = vars (factor(practice, levels=c("Manejo"), labels = c("Manejos")))) +
		guides (fill = guide_legend(nrow = 1)) + plot_setts + 
		theme(legend.position = "bottom", 
		      panel.grid.major.y = element_blank(),
		      panel.grid.major.x = element_line(color = "gray40", linewidth = 0.1, linetype = "dashed")) +
		coord_flip()

	figure4 <- origenes | (manejos + theme(axis.text.y = element_blank()))
	figure4 + plot_annotation(tag_levels = 'A', tag_suffix = ") ") &
		theme(plot.tag = element_text(size = 14, face = "bold"))
	
	ggplot2::ggsave(file = 'Figures/Fig.4-Sutrop.png', dpi = 300, device = "png", width = 10, height = 5)

```

## 5. Figura 5: Análisis de componentes principales - PCA de aceites esenciales

```{r,eval=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=40)}

# 5.1. Loading database -----------------------------------------------------

	# Load the raw database

	data <- read.table(file = 'data/db_Fig.5_PCA_aceites_esenciales.tsv', row.names = 1, header = T, sep = '\t')
	
	metadata <- data %>% 
		tibble::rownames_to_column(var = "TRATAMIENTO") %>% 
		select(1:4); head(metadata)

# 5.2. Transform data and determine the Principal Component Analysis  -------

	head(data)
	oil.pca <- FactoMineR::PCA(data[,8:ncol(data)], ncp = 4)

	# 5.2.1. Get individuals coordinates and merge with their metadata
	
	sam.coords <- data.frame (oil.pca$ind$coord, check.names = F) %>% 
		tibble::rownames_to_column(var = "TRATAMIENTO") %>% 
		dplyr::inner_join(x = metadata, by = "TRATAMIENTO")
	str(sam.coords)
	sam.coords %>% tibble::as_tibble()
	
	# 5.2.2. Get variables (essential oils) coordinates of the top 10 contributors for PC1 and PC2

	topcontrib <- data.frame(oil.pca$var$contrib, check.names = F) %>%
		tibble::rownames_to_column(var = "oil") %>% 
		dplyr::arrange(-Dim.1) %>% 
		dplyr::filter(!grepl(pattern = "TR-", x = oil)) %>% 
		filter(Dim.1 > 4); topcontrib
	
	# 5.3.3. Get variables (essential oils), and ignore those with unknown names
	
	responsevar <- data.frame(oil.pca$var$coord, check.rows = F, check.names = F) %>%
		tibble::rownames_to_column(var = "ResponseVar"); responsevar


# 5.3. Draw the Principal Component Analysis with ggplot2: PCA --------------
	
	p <- 
	ggplot() + theme_bw ()+
		labs (x = paste ("PC1 ", paste(base::round (oil.pca$eig[1,2], digits = 2), "%", sep = "")),
		      y = paste ("PC2 ", paste(base::round (oil.pca$eig[2,2], digits = 2), "%", sep = ""))) +
		# adding vectors: variables
		geom_segment(data = responsevar,
			     aes(x = 0, y = 0, xend = Dim.1*5, yend = Dim.2*5),
			     arrow = arrow(length = unit(0.15, "cm")),
			     color = "black", show.legend = NA) +
		## adding vectors names: variable names in front of each vector
		## Plot only the top 10 contributors per PC
		ggrepel::geom_label_repel(data = responsevar %>% 
					  	dplyr::filter(!grepl(pattern = 'TR-', x = ResponseVar)) %>% 
					  	dplyr::filter(ResponseVar %in% topcontrib$oil),
					  aes(x=Dim.1*7, y=Dim.2*7, label = ResponseVar),
					  segment.colour = NA, col = 'black', fill= "#FFFFFF",
					  fontface = "italic",  box.padding = 0.6, size = 5) +
		geom_point(data = sam.coords, aes (x = Dim.1, y = Dim.2, shape = SITIO, colour = CATEGORIAS), size = 5, alpha = 0.7) +
		stat_ellipse(data = sam.coords, aes(x=Dim.1, y=Dim.2, color = CATEGORIAS), type = "norm") +
		scale_color_manual(name = element_blank(), values = c("#E69F00", "#56B4E9")) +
		scale_shape_manual(name = element_blank(), values=c(15,19)) +
		scale_x_continuous(limits = c(-10,10), breaks = seq(from = -10, to = 10, by = 5)) +
		scale_y_continuous(limits = c(-10,15), breaks = seq(from = -10, to = 15, by = 5)) +
		geom_hline(yintercept=0, linetype="dashed", color = "black") +
		geom_vline (xintercept = 0, linetype="dashed", color = "black") +
		guides(fill = guide_legend(nrow = 2)) +
		theme(panel.grid = element_blank(),
		      legend.text = element_text(size = 12, color = "black"),
		      axis.text = element_text(size = 14, color = "black"),
		      axis.title = element_text(color = "black", size = 14),
		      legend.key = element_blank(),
		      ## legend.position:legend.position = c(0.85,0.85)
		      legend.position = "top")
	
	stats_data <- data.frame("Factor" = c("Sitio", "Categoría", "Interacción"),
	"P_value" = c(0.018, 0.140, 0.450),
	"R2" = c(0.080, 0.003, 0.110))
	
	stats_data %>% tibble::as_tibble()
	
	p + annotation_custom(tableGrob(stats_data, rows=NULL), 
			      xmin=3, xmax=10, ymin=10, ymax=15)
	ggplot2::ggsave(file = 'Figures/Fig.5.PCA-acei_esenciales.png', dpi = 300, device = "png", width = 7, height = 7)

```


## 6. Análisis multivariado: perMANOVA de contenido de aceites esenciales

```{r, eval=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=40)}
# 6. Multivariate analysis: perMANOVA -------------------------------------

	## perMANOVA: Using the filtered data
	# sink (file = 'data/permanova-eoils.txt') # to save the output to a plain text file
	# dist_essoils <- vegan::vegdist(x = data[,8:ncol(data)], method = "euclidean") # determine the distance matrix
	vegan::adonis2(formula = dist_essoils ~ SITIO * CATEGORIAS, data = data[,1:7], parallel = T, permutations = 9999) # determine perMANOVA
	# sink (file = NULL) # save the outpu
```



